<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Calendar;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCalendarIdBetweenDates(Calendar $calendar, array $dates)
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->where('b.calendar = :calendar')
            ->andWhere('b.startTime >= :startTime')
            ->andWhere('b.endTime <= :endTime')
            ->setParameter('startTime', $dates['start'])
            ->setParameter('endTime', $dates['end'])
            ->setParameter('calendar', $calendar)
        ;

        $queryResults = $qb->getQuery()->getArrayResult();
        return $queryResults;
    }
}
