<?php

namespace AppBundle\Repository;

/**
 * WorkingHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingHoursRepository extends \Doctrine\ORM\EntityRepository
{
}
