<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Calendar;
/**
 * WorkingHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingHoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function isAtWorkingHours(Calendar $calendar, array $data, $endDateTime)
    {

        $qb = $this->createQueryBuilder('w');
        $qb->where('w.calendar = :calendar')
            ->andWhere('w.startTime <= :startTime')
            ->andWhere('w.endTime >= :endTime')
            ->setParameter('calendar', $calendar)
            ->setParameter('startTime', $data['startTime'])
            ->setParameter('endTime', $endDateTime)
        ;

        $queryResults = $qb->getQuery()->getArrayResult();
        if (count($queryResults) > 0) {
            return true;
        } else {
            return false;
        }
    }
}
